OrdererOrgs:
- Name: Orderer
  Domain: dredev.de
  EnableNodeOUs: true
  Specs:
  - Hostname: orderer1
  - SANS:
    - localhost
    - 127.0.0.1
PeerOrgs:
- Name: Org1
  Domain: org1.dredev.de
  EnableNodeOUs: true
  Template:
    Count: 5
    SANS:
    - localhost
    - 127.0.0.1
  Users:
    Count: 1
